// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'i_vatan_app';
  static const String PROJECT_VERSION = '1.0.2+6';
  static const String I_APP = 'assets/images/i_app.jpeg';
  static const String REEL_LIKE = 'assets/images/reel_like.svg';
  static const String VERIFIED = 'assets/images/verified.jpeg';
}
