// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'i_vatan_app';
  static const String PROJECT_VERSION = '1.0.2+3';
  static const String DMSANS_BOLD = 'DMSans-Bold';
  static const String DMSANS_BOLDITALIC = 'DMSans-BoldItalic';
  static const String DMSANS_ITALIC = 'DMSans-Italic';
  static const String DMSANS_LIGHT = 'DMSans-Light';
  static const String DMSANS_MEDIUM = 'DMSans-Medium';
  static const String DMSANS_REGULAR = 'DMSans-Regular';
  static const String DMSANS_THIN = 'DMSans-Thin';
}
