// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Cpu1QVxlTDcMS-Rlxx7WTsFwWwMMH9Q',
    appId: '1:661840110268:web:9b8be86abbfe88a9f726b9',
    messagingSenderId: '661840110268',
    projectId: 'i-vatan-5ed0a',
    authDomain: 'i-vatan-5ed0a.firebaseapp.com',
    storageBucket: 'i-vatan-5ed0a.firebasestorage.app',
    measurementId: 'G-4JQ1SFHDJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfkZpuP9pwK_awmbDSLGjycq0JTqhOF-c',
    appId: '1:661840110268:android:5a2d26a164b2c3e4f726b9',
    messagingSenderId: '661840110268',
    projectId: 'i-vatan-5ed0a',
    storageBucket: 'i-vatan-5ed0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHdJ_gwCxvIK1il_Ssc9fKq1p__wJ9zx8',
    appId: '1:661840110268:ios:9f9a22b37575770cf726b9',
    messagingSenderId: '661840110268',
    projectId: 'i-vatan-5ed0a',
    storageBucket: 'i-vatan-5ed0a.firebasestorage.app',
    iosBundleId: 'com.example.iVatanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHdJ_gwCxvIK1il_Ssc9fKq1p__wJ9zx8',
    appId: '1:661840110268:ios:9f9a22b37575770cf726b9',
    messagingSenderId: '661840110268',
    projectId: 'i-vatan-5ed0a',
    storageBucket: 'i-vatan-5ed0a.firebasestorage.app',
    iosBundleId: 'com.example.iVatanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Cpu1QVxlTDcMS-Rlxx7WTsFwWwMMH9Q',
    appId: '1:661840110268:web:fa1c291d13c66c49f726b9',
    messagingSenderId: '661840110268',
    projectId: 'i-vatan-5ed0a',
    authDomain: 'i-vatan-5ed0a.firebaseapp.com',
    storageBucket: 'i-vatan-5ed0a.firebasestorage.app',
    measurementId: 'G-Q4PS3N5GKB',
  );
}
